# Generated by Django 5.2.7 on 2025-11-12 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_parentinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
