# Generated by Django 5.2.7 on 2025-11-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_attendance_marked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
