# Generated by Django 5.2.7 on 2025-11-05 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
        ('records', '0005_studentoffense'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentoffense',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee_offenses', to='records.student'),
        ),
    ]
