# Generated by Django 5.2.7 on 2025-10-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_address', models.TextField()),
                ('permanent_home_address', models.TextField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('lga', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('denomination', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('admission_no', models.CharField(max_length=50, unique=True)),
                ('nin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('class_on_entry', models.CharField(max_length=50)),
                ('date_of_entry', models.DateField()),
                ('class_at_present', models.CharField(max_length=50)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='students/images/')),
                ('father_name', models.CharField(max_length=100)),
                ('father_address', models.TextField(blank=True, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_educational_level', models.CharField(blank=True, max_length=100, null=True)),
                ('father_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_address', models.TextField(blank=True, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_educational_level', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_address', models.TextField(blank=True, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('prev_schools', models.TextField(blank=True, null=True)),
                ('visually_impaired', models.BooleanField(default=False)),
                ('deaf', models.BooleanField(default=False)),
                ('physically_disabled', models.BooleanField(default=False)),
                ('mentally_impaired', models.BooleanField(default=False)),
                ('others', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['admission_no'], name='records_stu_admissi_288fe4_idx'), models.Index(fields=['surname', 'other_name'], name='records_stu_surname_6bc491_idx'), models.Index(fields=['class_at_present'], name='records_stu_class_a_194f92_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('nin', 'National Identification Number (NIN)'), ('immunization_card', 'Immunization Card'), ('waec_result', 'WAEC Result'), ('neco_result', 'NECO Result'), ('transfer_certificate', 'Transfer Certificate'), ('testimonial', 'Testimonial'), ('passport', 'Passport Photo'), ('medical_report', 'Medical Report'), ('other', 'Other Document')], default='other', help_text='Type of document being uploaded', max_length=50)),
                ('name', models.CharField(help_text='Custom name/description for the document', max_length=100)),
                ('file', models.FileField(upload_to='students/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the document', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.student')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
