# Generated by Django 5.2.7 on 2025-10-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_populate_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(blank=True, editable=False, help_text='Automatically generated admission number', max_length=50, unique=True),
        ),
    ]
