# Generated by Django 5.2.7 on 2025-11-05 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_student_admission_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOffense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_type', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('description', models.TextField()),
                ('date_committed', models.DateField()),
                ('action_taken', models.TextField()),
                ('witness', models.CharField(blank=True, max_length=200, null=True)),
                ('documented_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_offenses', to='records.student')),
            ],
            options={
                'verbose_name': 'Student Offense',
                'verbose_name_plural': 'Student Offenses',
                'ordering': ['-date_committed'],
            },
        ),
    ]
