# Generated by Django 5.2.7 on 2025-11-07 11:11

import django.db.models.deletion
from django.db import migrations, models


def normalize_class_name(value: str) -> str:
    return "".join(value.split()).upper() if value else ""


def assign_classrooms(apps, schema_editor):
    Student = apps.get_model('records', 'Student')
    ClassRoom = apps.get_model('academics', 'ClassRoom')

    classroom_map = {}
    for classroom in ClassRoom.objects.all():
        classroom_map[normalize_class_name(f"{classroom.level}{classroom.arm}")] = classroom

    for student in Student.objects.filter(classroom__isnull=True):
        normalized = normalize_class_name(student.class_at_present)
        classroom = classroom_map.get(normalized)
        if classroom:
            student.classroom_id = classroom.id
            student.class_at_present = str(classroom)
            student.save(update_fields=['classroom', 'class_at_present', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('records', '0005_studentoffense'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text="Select the student's current class", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_at_present',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(assign_classrooms, migrations.RunPython.noop),
    ]
