# Generated by Django 5.2.7 on 2025-11-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_student_classroom_alter_student_class_at_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_at_present',
            field=models.CharField(max_length=50),
        ),
    ]
