# Generated by Django 5.2.7 on 2025-11-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_student_class_at_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active students are shown in lists. Unselect this to archive a student.'),
        ),
    ]
