# Generated by Django 5.2.7 on 2025-11-09 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_studentscore_grade_studentscore_percentage_and_more'),
        ('records', '0008_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_session',
            field=models.ForeignKey(blank=True, help_text='The academic session the student graduated/was archived in.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicsession'),
        ),
    ]
