# Generated by Django 5.2.7 on 2025-11-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_studentscore_grade_studentscore_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='attendance_in_class',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor'), (0, 'N/A')], default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='handwriting',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor'), (0, 'N/A')], default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='honesty',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor'), (0, 'N/A')], default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='neatness',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor'), (0, 'N/A')], default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='punctuality',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor'), (0, 'N/A')], default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='sports_and_games',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor'), (0, 'N/A')], default=0),
        ),
    ]
