# Generated by Django 5.2.7 on 2025-11-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
