# Generated by Django 5.1.7 on 2025-11-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_assessment_is_published_assessment_published_at'),
        ('records', '0010_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcard',
            options={'ordering': ['-term__session__start_date', 'student__surname'], 'verbose_name': 'Report Card', 'verbose_name_plural': 'Report Cards'},
        ),
        migrations.AddField(
            model_name='reportcard',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Attendance percentage (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='benchmark_data',
            field=models.JSONField(blank=True, default=dict, help_text='Store benchmark data: class_avg, national_avg, target_score'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='color_coded_performance',
            field=models.CharField(choices=[('Green', 'Excellent (Top Performer)'), ('Blue', 'Good (High Performer)'), ('Yellow', 'Average (Meets Standard)'), ('Orange', 'Fair (Below Standard)'), ('Red', 'Poor (Intervention Needed)')], default='Yellow', help_text='Color indicator for quick performance assessment', max_length=50),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='creative_skills',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor'), (0, 'N/A')], default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='discipline',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor'), (0, 'N/A')], default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes for staff (not visible to students)'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='next_term_recommendation',
            field=models.CharField(blank=True, choices=[('Promoted', 'Promoted to next class'), ('Promoted with Caution', 'Promoted with caution'), ('Retained', 'Retained in same class'), ('Special Intervention', 'Special intervention needed'), ('Referred to Counselor', 'Referred to counselor')], help_text='Academic recommendation for next term', max_length=100),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='participation',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor'), (0, 'N/A')], default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='performance_trend',
            field=models.CharField(choices=[('Improving', 'Improving'), ('Stable', 'Stable'), ('Declining', 'Declining'), ('Inconsistent', 'Inconsistent')], default='Stable', help_text='Trend compared to previous term', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', help_text='Report card status for workflow management', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['status', 'term'], name='academics_r_status_58b8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['student', 'term'], name='academics_r_student_306482_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['-published_at'], name='academics_r_publish_88eae9_idx'),
        ),
    ]
