# Generated by Django 5.1.7 on 2025-11-19 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_reportcard_options_reportcard_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-date'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AlterModelOptions(
            name='studentscore',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Student Score', 'verbose_name_plural': 'Student Scores'},
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_code',
            field=models.CharField(choices=[('CA1', 'CA 1 (0-10)'), ('CA2', 'CA 2 (0-10)'), ('CA3', 'CA 3 (0-10+)'), ('TEST', 'Test (0-10)'), ('EXAM', 'Exam (0-60)')], default='CA1', help_text='Assessment category (CA must be <=10, max CA total=40; Exam=60)', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When locked, scores cannot be edited'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When the scores were locked', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='Admin who locked the scores', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_locked', to=settings.AUTH_USER_MODEL),
        ),
    ]
